/**
 * Zotero 只读客户端的单测。
 *
 * 两条纪律（本仓库踩过的坑）：
 *   1. 测试数据用**本机实测的真值**（真实的 prefs.js 片段、真实的 file:// URL、真实的
 *      annotationPosition JSON），不用编造的漂亮数据 —— 编造的数据测不出真问题。
 *   2. HTTP 用**注入的 fetch 桩**，桩的行为贴近真实语义（403 带什么 body、children 空库返回
 *      什么）——否则"探测失败"的分支永远测不到。
 */
const path = require('path');
const fs = require('fs');
const assert = require('assert');

const CLIENT = path.join(__dirname, '..', '..', 'dist-test', 'zoteroClient.js');

let zc;
try {
  zc = require(CLIENT);
} catch (e) {
  console.error(`\n❌ 找不到被测文件 ${CLIENT}\n   先跑： npx tsc src/zoteroClient.ts --outDir dist-test --module commonjs --target es2020 --skipLibCheck\n`);
  console.error(String(e && e.message));
  process.exit(1);
}

let pass = 0;
let fail = 0;
const failures = [];
function t(name, fn) {
  try {
    fn();
    pass++;
    console.log(`  ✅ ${name}`);
  } catch (e) {
    fail++;
    failures.push(`${name}\n     ${(e && e.message) || e}`);
    console.log(`  ❌ ${name}\n     ${(e && e.message) || e}`);
  }
}

console.log('===== Zotero 客户端单测 =====\n');

// ---------------------------------------------------------------------------
console.log('【1】prefs.js 解析（真实文件形态）');
// ---------------------------------------------------------------------------
// 真值取样：本机 %APPDATA%\Zotero\Zotero\Profiles\iw79jc85.default\prefs.js
const REAL_PREFS = `// Mozilla User Preferences

// Do not edit this file.
//
user_pref("extensions.zotero.debug.log", false);
user_pref("extensions.zotero.httpServer.enabled", true);
user_pref("extensions.zotero.httpServer.port", 23119);
user_pref("extensions.zotero.httpServer.localAPI.enabled", true);
user_pref("extensions.zotero.firstRun2", false);
`;
const PREF = zc.ZOTERO_LOCAL_API_PREF;

t('真实 prefs.js 里读到 localAPI=true', () => {
  assert.strictEqual(zc.readBoolPref(REAL_PREFS, PREF), true);
});
t('没写这一行时返回 null（而不是 false）——必须能和"明确关掉"区分开', () => {
  const withoutLine = REAL_PREFS.replace(/^.*localAPI.*\n/m, '');
  assert.strictEqual(zc.readBoolPref(withoutLine, PREF), null);
});
t('明确写成 false 时读到 false', () => {
  const off = REAL_PREFS.replace('localAPI.enabled", true', 'localAPI.enabled", false');
  assert.strictEqual(zc.readBoolPref(off, PREF), false);
});
t('pref 名里的点不会被当成通配（其余 pref 不能误命中）', () => {
  const other = `user_pref("extensionsXzoteroXhttpServerXlocalAPIXenabled", true);`;
  assert.strictEqual(zc.readBoolPref(other, PREF), null);
});
t('端口 pref 用同一个解析器也能读到（证明不是硬编码）', () => {
  assert.strictEqual(zc.readBoolPref(REAL_PREFS, 'extensions.zotero.httpServer.port'), null, '端口是数字，布尔解析器应返回 null');
});

// ---------------------------------------------------------------------------
console.log('\n【2】file:// URL 解析（含中文与空格，本机真实文件名）');
// ---------------------------------------------------------------------------
// 真值取样：/api/users/0/items/NQI6N4AP 的 links.enclosure.href
const REAL_HREF =
  'file:///C:/Users/paroxetine/Zotero/storage/NQI6N4AP/Oh%20%E7%AD%89%20-%202019%20-%20Video%20Object%20Segmentation%20Using%20Space-Time%20Memory%20Networks.pdf';

t('解析出 storage key 与解码后的文件名', () => {
  const r = zc.parseFileUrl(REAL_HREF);
  assert.strictEqual(r.storageKey, 'NQI6N4AP');
  assert.strictEqual(r.fileName, 'oh 等 - 2019 - video object segmentation using space-time memory networks.pdf');
});
t('filePath 已去掉 file:/// 前缀并统一斜杠、小写', () => {
  const r = zc.parseFileUrl(REAL_HREF);
  assert.ok(r.filePath.startsWith('c:/users/paroxetine/zotero/storage/nqi6n4ap/'), r.filePath);
});
t('文件名里有裸 % 时不会抛异常（decodeURIComponent 会 throw，必须兜住）', () => {
  const r = zc.parseFileUrl('file:///C:/tmp/50%25done%20x%2.pdf');
  assert.strictEqual(typeof r.fileName, 'string');
  assert.ok(r.fileName.length > 0);
});
t('空 href 不崩', () => {
  assert.deepStrictEqual(zc.parseFileUrl(undefined), { fileName: '', storageKey: '', filePath: '' });
});

// ---------------------------------------------------------------------------
console.log('\n【3】论文认领（宁可认不出，也不许认错）');
// ---------------------------------------------------------------------------
function mkItem(key, fileName, { size = 1000, title = 'T', contentType = 'application/pdf' } = {}) {
  return {
    key,
    links: {
      enclosure: {
        href: `file:///C:/Users/x/Zotero/storage/${key}/${encodeURIComponent(fileName)}`,
        // 真机响应的 enclosure 就带 title（= 文件名）与 length，桩必须照抄，否则测的是空气
        title: fileName,
        length: size,
        type: contentType
      }
    },
    data: { key, itemType: 'attachment', contentType, title, filename: fileName }
  };
}
const ITEMS = [
  mkItem('AAAA1111', 'Yang 等 - Associating Objects with Transformers.pdf', { size: 3428086 }),
  mkItem('BBBB2222', 'Oh 等 - 2019 - STM.pdf', { size: 4030776 }),
  mkItem('CCCC3333', 'not-a-pdf.txt', { size: 10, contentType: 'text/plain' })
];

t('完整路径一致 → matchedBy=path', () => {
  const r = zc.matchZoteroItem('C:\\Users\\x\\Zotero\\storage\\BBBB2222\\Oh 等 - 2019 - STM.pdf', undefined, ITEMS);
  assert.strictEqual(r.matchedBy, 'path');
  assert.strictEqual(r.item.key, 'BBBB2222');
});
t('只有文件名一致（用户把 PDF 拷到别处打开）→ matchedBy=basename', () => {
  const r = zc.matchZoteroItem('D:\\论文\\Oh 等 - 2019 - STM.pdf', undefined, ITEMS);
  assert.strictEqual(r.matchedBy, 'basename');
  assert.strictEqual(r.item.key, 'BBBB2222');
});
t('文件名对不上但有唯一同大小 → matchedBy=size', () => {
  const r = zc.matchZoteroItem('D:\\下载\\yang_aot_final.pdf', 3428086, ITEMS);
  assert.strictEqual(r.matchedBy, 'size');
  assert.strictEqual(r.item.key, 'AAAA1111');
});
t('完全不相关 → null（必须什么都不做，而不是猜一个）', () => {
  assert.strictEqual(zc.matchZoteroItem('D:\\无关\\other.pdf', 999, ITEMS), null);
});
t('同名两条且大小无法消歧 → null（错认比认不出更糟）', () => {
  const dup = [
    mkItem('DDDD4444', 'same.pdf', { size: 1 }),
    mkItem('EEEE5555', 'same.pdf', { size: 2 })
  ];
  assert.strictEqual(zc.matchZoteroItem('D:\\x\\same.pdf', 3, dup), null);
});
t('非 PDF 附件不参与匹配', () => {
  assert.strictEqual(zc.matchZoteroItem('D:\\x\\not-a-pdf.txt', 10, ITEMS), null);
});

// ---------------------------------------------------------------------------
console.log('\n【4】元数据整形（真值是本机 Zotero 里这三篇的实际字段）');
// ---------------------------------------------------------------------------
t('作者数 ≤2 用 & 连接，≥3 用 et al.', () => {
  const att = mkItem('K', 'a.pdf');
  const one = zc.formatZoteroMeta({ key: 'P', data: { title: 'A', itemType: 'conferencePaper', creators: [{ lastName: 'Yang', firstName: 'Zongxin' }] } }, att);
  assert.strictEqual(one.creators, 'Yang Zongxin');
  const two = zc.formatZoteroMeta({ key: 'P', data: { title: 'A', itemType: 'conferencePaper', creators: [{ lastName: 'Yang' }, { lastName: 'Wei' }] } }, att);
  assert.strictEqual(two.creators, 'Yang & Wei');
  const three = zc.formatZoteroMeta(
    { key: 'P', data: { title: 'A', itemType: 'conferencePaper', creators: [{ lastName: 'Yang' }, { lastName: 'Wei' }, { lastName: 'Yi' }] } },
    att
  );
  assert.strictEqual(three.creators, 'Yang et al.');
});
t('单字段 name 型作者（机构作者）也能取到', () => {
  const meta = zc.formatZoteroMeta({ key: 'P', data: { title: 'A', creators: [{ name: 'Adobe Research' }] } }, mkItem('K', 'a.pdf'));
  assert.strictEqual(meta.creators, 'Adobe Research');
});
t('年份从 Zotero 日期串里取四位年（含 "2021-10-01 2021" 这种形态）', () => {
  assert.strictEqual(zc.yearFromZoteroDate('2021-10-01 2021'), '2021');
  assert.strictEqual(zc.yearFromZoteroDate('2019'), '2019');
  assert.strictEqual(zc.yearFromZoteroDate(''), '');
  assert.strictEqual(zc.yearFromZoteroDate('n.d.'), '');
});
t('会议论文取 proceedingsTitle，期刊取 publicationTitle', () => {
  const att = mkItem('K', 'a.pdf');
  const conf = zc.formatZoteroMeta({ key: 'P', data: { title: 'A', proceedingsTitle: 'ICCV' } }, att);
  assert.strictEqual(conf.venue, 'ICCV');
  const jour = zc.formatZoteroMeta({ key: 'P', data: { title: 'A', publicationTitle: 'TPAMI' } }, att);
  assert.strictEqual(jour.venue, 'TPAMI');
});
t('summary 形如「作者 · 年 · 会议」，空字段不留下多余分隔符', () => {
  const meta = zc.formatZoteroMeta(
    { key: 'P', data: { title: 'A', creators: [{ lastName: 'Yang' }], date: '2021', proceedingsTitle: 'ICCV' } },
    mkItem('K', 'a.pdf')
  );
  assert.strictEqual(meta.summary, 'Yang · 2021 · ICCV');
  const bare = zc.formatZoteroMeta({ key: 'P', data: { title: '', creators: [] } }, mkItem('K', 'from-file-name.pdf'));
  assert.strictEqual(bare.summary, '');
  assert.strictEqual(bare.title, 'from-file-name', '父条目没标题时退回附件文件名（去 .pdf）');
});
t('附件的占位标题（PDF / Full Text PDF / 单字符 T）不能被当成论文标题', () => {
  assert.strictEqual(zc.isPlaceholderTitle('PDF'), true);
  assert.strictEqual(zc.isPlaceholderTitle('Full Text PDF'), true);
  assert.strictEqual(zc.isPlaceholderTitle('T'), true, '用户在 Zotero 里手改成的单字符也是占位');
  assert.strictEqual(zc.isPlaceholderTitle(''), true);
  assert.strictEqual(zc.isPlaceholderTitle('Video Object Segmentation using STM'), false);
  // 真值来自本机 Zotero：Oh 那篇附件的 data.title 就是 "PDF"
  const info = mkItem('K', 'Oh 等 - 2019 - STM.pdf');
  info.data.title = 'PDF';
  const meta = zc.formatZoteroMeta({ key: 'P', data: { title: '', creators: [] } }, info);
  assert.strictEqual(meta.title, 'Oh 等 - 2019 - STM', '退回文件名时保留原始大小写，不跟着匹配用的归一化串走');
});

// ---------------------------------------------------------------------------
console.log('\n【5】批注坐标（口径错了会在错位置画高亮，比不画更糟）');
// ---------------------------------------------------------------------------
t('annotationPosition 解析成功 / 坏 JSON 返回 null', () => {
  const p = zc.parseAnnotationPosition('{"pageIndex":3,"rects":[[100,200,300,220]]}');
  assert.strictEqual(p.pageIndex, 3);
  assert.deepStrictEqual(p.rects[0], [100, 200, 300, 220]);
  assert.strictEqual(zc.parseAnnotationPosition('{oops'), null);
  assert.strictEqual(zc.parseAnnotationPosition(undefined), null);
});
t('PDF 坐标（原点左下）翻成左上原点：top = pageHeight - y2', () => {
  // 页面高 792（Letter），高亮在 y=200..220 → 翻转后 y=572..592
  const r = zc.rectToTopDown([100, 200, 300, 220], 792);
  assert.deepStrictEqual(r, { x: 100, y: 572, w: 200, h: 20 });
});
t('x1/x2 或 y1/y2 倒着写也能归一化（Zotero 存的顺序不保证）', () => {
  const r = zc.rectToTopDown([300, 220, 100, 200], 792);
  assert.deepStrictEqual(r, { x: 100, y: 572, w: 200, h: 20 });
});
t('非法矩形返回 null（不画比画错好）', () => {
  assert.strictEqual(zc.rectToTopDown([1, 2], 792), null);
  assert.strictEqual(zc.rectToTopDown([1, NaN, 3, 4], 792), null);
});
t('annotationType 映射：underline 归到高亮，text 归到笔记', () => {
  assert.strictEqual(zc.mapAnnotationKind('highlight'), 'highlight');
  assert.strictEqual(zc.mapAnnotationKind('underline'), 'highlight');
  assert.strictEqual(zc.mapAnnotationKind('note'), 'note');
  assert.strictEqual(zc.mapAnnotationKind('text'), 'note');
  assert.strictEqual(zc.mapAnnotationKind('ink'), 'ink');
  assert.strictEqual(zc.mapAnnotationKind(undefined), 'highlight');
});

// ---------------------------------------------------------------------------
console.log('\n【6】逐页全文与页数校验（错位是静默的，必须显式判废）');
// ---------------------------------------------------------------------------
t('按 \\f 切页：本机实测 3 页样例切成 3 段', () => {
  const r = zc.splitFullTextPages('p1 text\fp2 text\fp3 text', 3, 3, 3);
  assert.strictEqual(r.pages.length, 3);
  assert.strictEqual(r.pages[1], 'p2 text');
  assert.strictEqual(r.indexedPages, 3);
  assert.strictEqual(r.pageCountMismatch, false);
});
t('索引页数与本地 PDF 页数不一致 → pageCountMismatch=true', () => {
  const r = zc.splitFullTextPages('p1\fp2', 2, 10, 10);
  assert.strictEqual(r.pageCountMismatch, true, '只索引了 2 页而 PDF 有 10 页，必须判废');
});
t('结尾多余空段被丢掉（本机实测无尾空段，但换行差异不能造成假的不一致）', () => {
  const r = zc.splitFullTextPages('p1\fp2\f', 2, 2, 2);
  assert.strictEqual(r.pages.length, 2);
  assert.strictEqual(r.pageCountMismatch, false);
});
t('空全文不会崩，且 chars=0', () => {
  const r = zc.splitFullTextPages('', 0, 0, 8);
  assert.strictEqual(r.chars, 0);
});

// ---------------------------------------------------------------------------
console.log('\n【7】探测：三种失败必须区分（用户的下一步动作完全不同）');
// ---------------------------------------------------------------------------
function stubFetch(routes) {
  // 用 RegExp 精确匹配路径，按顺序返回第一个命中的路由。
  // 【踩过的坑】早先版本用 `url.includes(pattern)`，`/items?itemType=attachment` 这个模式
  // 会把 `/items/BBBB2222` 也一起吞掉，于是拿单个条目时返回了一个数组，
  // 认领在"取父条目"那一步静默失败。桩必须能表达"这两条路径是不同端点"。
  return async (url) => {
    const u = String(url);
    for (const [pattern, resp] of routes) {
      if (new RegExp(pattern).test(u)) {
        const r = typeof resp === 'function' ? resp(u) : resp;
        return {
          ok: r.status >= 200 && r.status < 300,
          status: r.status,
          headers: { get: (k) => (r.headers || {})[k] || null },
          text: async () => r.body || ''
        };
      }
    }
    return { ok: false, status: 404, headers: { get: () => null }, text: async () => 'No endpoint found' };
  };
}

(async () => {
  // ① 没开本地 API：真机上就是这个 403 + 这段 body
  const disabled = new zc.ZoteroClient({
    fetchImpl: stubFetch([['/api/$', { status: 403, body: 'Local API is not enabled' }]])
  });
  const d1 = await disabled.detect(true);
  t('403 Local API is not enabled → reason=api-disabled，且提示里带"怎么开"', () => {
    assert.strictEqual(d1.available, false);
    assert.strictEqual(d1.reason, 'api-disabled');
    assert.ok(/设置/.test(d1.message) && /允许/.test(d1.message), d1.message);
  });

  // ② Zotero 没开：fetch 直接 ECONNREFUSED
  const down = new zc.ZoteroClient({
    fetchImpl: async () => {
      throw new Error('connect ECONNREFUSED 127.0.0.1:23119');
    }
  });
  const d2 = await down.detect(true);
  t('连不上 → reason=not-running', () => {
    assert.strictEqual(d2.reason, 'not-running');
    assert.ok(/Zotero/.test(d2.message));
  });

  // ③ 正常可用：真机的 /api/ 返回头里有 X-Zotero-Version
  const ok = new zc.ZoteroClient({
    fetchImpl: stubFetch([['/api/$', { status: 200, body: 'Nothing to see here.', headers: { 'X-Zotero-Version': '9.0.6' } }]])
  });
  const d3 = await ok.detect(true);
  t('200 → available=true 且带出 Zotero 版本', () => {
    assert.strictEqual(d3.available, true);
    assert.strictEqual(d3.version, '9.0.6');
  });

  // ④ 全文 404（附件没被索引过）
  const noIndex = new zc.ZoteroClient({
    fetchImpl: stubFetch([
      ['/api/$', { status: 200, body: '' }],
      ['/items\\?itemType=attachment', { status: 200, body: '[]' }]
    ])
  });
  const r4 = await noIndex.linkPdf('D:\\a\\b.pdf', {});
  t('库里没有匹配条目 → link=null 但 detect.available=true（不能把"没认领"说成"没连上"）', () => {
    assert.strictEqual(r4.link, null);
    assert.strictEqual(r4.detect.available, true);
  });

  // ⑤ 端到端（桩）：认领 → 取父条目 → 取全文 → 取批注
  const e2e = new zc.ZoteroClient({
    fetchImpl: stubFetch([
      ['/api/$', { status: 200, body: '' }],
      ['/items\\?itemType=attachment', {
        status: 200,
        body: JSON.stringify([
          {
            key: 'BBBB2222',
            links: {
              up: { href: 'http://localhost:23119/api/users/0/items/PAPER001' },
              enclosure: { href: 'file:///C:/Users/x/Zotero/storage/BBBB2222/Oh%20%E7%AD%89%20-%20STM.pdf', length: 4030776 }
            },
            data: { key: 'BBBB2222', itemType: 'attachment', contentType: 'application/pdf', filename: 'Oh 等 - STM.pdf' }
          }
        ])
      }],
      ['/items/PAPER001$', {
        status: 200,
        body: JSON.stringify({
          key: 'PAPER001',
          data: {
            key: 'PAPER001',
            itemType: 'conferencePaper',
            title: 'Video Object Segmentation using Space-Time Memory Networks',
            date: '2019',
            proceedingsTitle: 'ICCV',
            DOI: '10.1109/ICCV.2019.00932',
            creators: [{ lastName: 'Oh', firstName: 'Seoung Wug' }, { lastName: 'Lee' }, { lastName: 'Xu' }]
          }
        })
      }],
      ['/fulltext$', { status: 200, body: JSON.stringify({ content: 'A\fB\fC', indexedPages: 3, totalPages: 3 }) }],
      ['/children$', {
        status: 200,
        body: JSON.stringify([
          { key: 'ANNO1', data: { itemType: 'annotation', annotationType: 'highlight', annotationText: 'gy, Zhejian', annotationColor: '#ffd400', annotationPosition: '{"pageIndex":0,"rects":[[1,2,3,4]]}' } },
          { key: 'NOTE1', data: { itemType: 'note', note: '<p>x</p>' } }
        ])
      }]
    ])
  });
  const r5 = await e2e.linkPdf('D:\\论文\\Oh 等 - STM.pdf', { fileSize: 4030776, expectedPages: 3 });
  t('端到端：认领成功、元数据/全文/批注三项都到位', () => {
    assert.ok(r5.link, '应该认领成功');
    assert.strictEqual(r5.link.attachmentKey, 'BBBB2222');
    assert.strictEqual(r5.link.parentKey, 'PAPER001');
    assert.strictEqual(r5.link.matchedBy, 'basename');
    assert.strictEqual(r5.link.meta.year, '2019');
    assert.strictEqual(r5.link.meta.venue, 'ICCV');
    assert.strictEqual(r5.link.meta.creators, 'Oh et al.');
    assert.strictEqual(r5.link.meta.doi, '10.1109/ICCV.2019.00932');
    assert.strictEqual(r5.link.fullText.pages.length, 3);
    assert.strictEqual(r5.link.annotations.length, 1, 'note 子条目不是 annotation，必须被过滤掉');
    assert.strictEqual(r5.link.annotations[0].key, 'ANNO1');
  });
  t('页数不一致时 link 仍然成，但 fullText.pageCountMismatch=true（交调用方判废）', async () => {
    const mism = new zc.ZoteroClient({
      fetchImpl: stubFetch([
        ['/api/$', { status: 200, body: '' }],
        ['/items\\?itemType=attachment', {
          status: 200,
          body: JSON.stringify([
            {
              key: 'BBBB2222',
              links: { enclosure: { href: 'file:///C:/x/Oh%20%E7%AD%89%20-%20STM.pdf', length: 1 } },
              data: { key: 'BBBB2222', contentType: 'application/pdf', filename: 'x.pdf' }
            }
          ])
        }],
        ['/fulltext$', { status: 200, body: JSON.stringify({ content: 'A\fB', indexedPages: 2, totalPages: 2 }) }],
        ['/children$', { status: 200, body: '[]' }]
      ])
    });
    const r = await mism.linkPdf('D:\\x\\Oh 等 - STM.pdf', { expectedPages: 10 });
    assert.strictEqual(r.link.fullText.pageCountMismatch, true);
  });

  // ---------------------------------------------------------------------------
  console.log('\n【8】真机联调（可选）：直接打本机正在跑的 Zotero');
  // ---------------------------------------------------------------------------
  // 默认开启；设 ZOTERO_REAL_TEST=0 可跳过 —— 用来二分定位"非零退出"到底出在桩测试还是真机请求。
  // 这里刻意用 fetchImpl: null 走 Node 原生 http 路径：既覆盖了"没有全局 fetch"的兜底，
  // 也避开 undici 在 Windows 上退出时撞 libuv 断言的已知问题。
  const real = new zc.ZoteroClient({ timeoutMs: 4000, fetchImpl: null });
  if (process.env.ZOTERO_REAL_TEST === '0') {
    console.log('  ℹ️  ZOTERO_REAL_TEST=0，跳过真机联调');
    const realDetect = { available: false };
    void realDetect;
  } else {
  const realDetect = await real.detect(true);
  if (realDetect.available) {
    console.log(`  ℹ️  真机 Zotero ${realDetect.version || '?'} 可用，做一次真实认领`);
    const links = await real.listPdfAttachments(true);
    console.log(`     库里 PDF 附件 ${links.length} 个`);
    if (links.length) {
      const href = links[0].links && links[0].links.enclosure && links[0].links.enclosure.href;
      const name = zc.parseFileUrl(href).fileName;
      const link = await real.linkPdf(name, { expectedPages: undefined });
      t('真机：用真实文件名认领到条目，并拿到全文与元数据', () => {
        assert.ok(link.link, '应该认领到');
        assert.ok(link.link.fullText, '应该有全文');
        assert.ok(link.link.fullText.pages.length > 5, `页数应 >5，实际 ${link.link.fullText ? link.link.fullText.pages.length : 0}`);
        console.log(`     认领到《${link.link.meta.title}》 ${link.link.meta.summary}`);
        console.log(`     全文 ${link.link.fullText.pages.length} 页 / ${link.link.fullText.chars} 字，页数一致=${!link.link.fullText.pageCountMismatch}`);
        console.log(`     批注 ${link.link.annotations.length} 条`);
      });
    }
  } else {
    console.log(`  ℹ️  真机 Zotero 不可用（${realDetect.reason}）：${realDetect.message}`);
    console.log('     跳过硬联调；上面的桩测试已覆盖同一批代码路径。');
  }
  }
  /*
   * 用同步写输出结果，并且**不调用 process.exit()**。
   *
   * 【为什么】实测（Windows / Node 24）：真机联调那一段的输出量较大时，
   * console.log 的异步写还没落盘就 process.exit()，libuv 会在关句柄时撞
   * `Assertion failed: !(handle->flags & UV_HANDLE_CLOSING)`，退出码变成
   * 0xC0000409 —— 测试全绿、门禁却判失败（这个坑连查了三轮才定位到"输出量"这个变量）。
   * 所以：同步写 + 只设 exitCode，让 Node 自己排空后自然退出。
   */
  const report = [`\n===== 结果: ${pass} 通过 / ${fail} 失败 =====`];
  if (fail) {
    report.push('\n失败明细：');
    failures.forEach(f => report.push('  - ' + f));
  }
  report.push('');
  fs.writeSync(1, report.join('\n'));
  process.exitCode = fail ? 1 : 0;
})();
